### ISSUE TITLE
Please guys, some kind of Tutorial.

### ISSUE THREAD

**Issue by pvtpaula** [Nolenz/WurstMod#25]
I'd really like to make one or two maps for the game, but unfortunatly i'm a total pleb. I have zero experience in Unity AND coding. Basically, 

-I don't know how to install your mods and tool into Unity, it gives me like 100 errors evertime

-I cant export levels in the format everyone uses (leveldata), so i can't even test them. 

I won't demand someone to teach me unity for free, if its too complicated i gotta let it go. But damn there are guys saying they have no experience and they, made it to a point where i can play on there maps, so it can't be that difficult right? Mabe i'm just missing something, a helping hand would be very nice.

Thanks

**Comment by nrgill28** [comment]
Under the wiki section of the GitHub repo we have a number of guides and references for various things, one of which is a guide for setting up a mapping environment and checking that everything works. I covered pretty much the entire process so it should be straight forward. If you've already tried following it or have any issues while following it, please let me know.
https://github.com/Nolenz/WurstMod/wiki/Setting-up-your-environment

**Comment by pvtpaula** [comment]
Thank you for your time. Last weekend i found your guide and immediatley made good progress. 
I have now new problems, but they are mostly unity related:

-I can setup levels, but when i want to export them it says Occlusoin and Navmesh data is missing. I found them in the Scene, Prefabs but i don't know what to do with them 

-For now I'm testing around with the Debug Scenes, but there I encounter a problem where can place objects and assets but those assets dont have player collision, weapon collision is good tho.
When i want player collision i have to create a 3D object and then change everything, mesh, colliders, shaders, by hand, which is a bit of a process. Am I doing something wrong or is it because of the Debug Level itself? Can i use the debug level as a template?

**Comment by nrgill28** [comment]
Ah, yes.
The occlusion and navigation windows can be accessed under the Window menubar, just bake them with the default values.
The collision stuff is actually something I forgot to mention in the guide I linked earlier so I've updated that now.

In your project folder there is a `ProjectSettings/TagManager.asset` file, download the file of the same name from the most recent release (you'll be looking for v2 and not v2.0.1 here because it hasn't changed) and replace the file in your project with the downloaded one

Finally, stick anything that should have collision on the environment layer in Unity, this will give it player collision

**Comment by pvtpaula** [comment]
Awsome! Thank you very much!

I will surely break something else, and I guarantie you, I will come back here ;)

**Comment by pvtpaula** [comment]
Here I am again! 

Threw together a simple test map and was able to export it. Unfortunately the collisions still didn't work. The player is spawning a bit in the air, as to not spawn partly underground, and then falls throuh it. All Sosigs are rolling on the ground trying to shoot me.

Colliders are turned on. I'm using an asset pack, mabe its a problem with those? Did not test simple 3D Objects.  
I put all assets in "GEO layer" (an Empty i named GEO) like in the debug scenes, is that the aforementioned "enviroment layer"?

**Comment by Frityet** [comment]
Make sure the objects are set to static (top right checkbox after you click
an object) and that they have the environment layer (top right where it
says layers)

**Comment by pvtpaula** [comment]
Thank you, it was in fact the layer I had not assigned it. I'm learning so much today!

Okay next thing: 

-objects are flickering in and out of existence, depending on where i'm standing and where i'm looking. Almost as if they get culled at the wrong times

-shadows are harsh. like almost black can i lighten them up a bit, is it just playing around with the lighting?

**Comment by nrgill28** [comment]
Lighting is a little bit of a special case here. The game uses a set of shaders called Alloy, which can be downloaded from [their GitHub](https://github.com/Josh015/Alloy/tree/unity-5-6/). Just using Alloy shaders is an improvement, but if you really want lighting to look proper you will need to use the [Bakery lightmapper](https://assetstore.unity.com/packages/tools/level-design/bakery-gpu-lightmapper-122218), a paid Unity asset. 

For objects flickering there might be a few things that can cause that. I've had some weird visual glitches in the past that were solved by opening the player settings (Edit > Project Settings > Player) then in the Other Settings tab enabling Virtual Reality support, making sure you have the Oculus and OpenVR SDKs selected. Lastly, ensure you select Single Pass for the stereo rending method.

If that doesn't solve it then the occlusion culling could just have been applied really aggressively, so you can also toy with those options too.

**Comment by NikoWZRD** [comment]
To add to this, if the objects are flickering in and out of existence around where you're spawning, it's likely because you left your map at 0,0,0 on the unity scene, and it's overlapping with the vanilla TnH map's occlusion. Move your entire map up a fair bit and rebake your navmeshes & occlusion and it should correct that weird flickering.

**Comment by pvtpaula** [comment]
Will the lightbakery work with H3VR? Really consider buying.

Yes I build the map on the 0,0,0 coordinates, so i will try moving her uo to like y50. Thank you.

I hope this thread helps more people than just me, Thanks for the directions.

**Comment by nrgill28** [comment]
Yes, the Bakery asset does work with H3VR, it's actually what Anton uses too. I would like to make an FAQ page or similar for WurstMod so the stuff in here will eventually make its way out somewhere more accessible.

**Comment by pvtpaula** [comment]
Okay, Next plroblem XD

I have the map almost ready, wanted to test her. But while baking the Navmesh it just hangs in the beginning of 
7/11 Light Transport with 153 Jobs. Can i do anything about it? Mabe i forgott something, idk.

**Comment by pvtpaula** [comment]
Sorry for double posting,

My previous problem just went away, don't know why. The map is now ready, i could export it easyly (please someone tell how to wright that word), it loads, and seems to have good performance. 

But, on every start it spawns me at the scoreboard and i cant move, the radar shows that the hold and supplypoints are spawned. But i can't do anything. 
Just tested it for Sandbox. and its the same.  Mabe the navmesh is broken? It gave me some trouble, but i the AI can move freely.

I've backtraced my steps, switched stuff around. But i can't find whats wrong all of a sudden. In early testing it was okay, but now i have put hours into it an it doesn't work, its frustrating. If someone knows what could be causing that problem please.... any guess is appreciated

**Comment by nrgill28** [comment]
Without being able to see the scene myself I can't fully help with this, but based on what you've included in your message I think I have a pretty good guess as to what is causing this behaviour. 

I believe you've placed a game object with the `Spawn` component down in your scene, something that is not required for Take and Hold levels but IS required for sandbox levels. So because you were even able to export your scene as a sandbox level it means you do in fact have one of these somewhere in your scene. The `Spawn` component will move the player to it's position when the scene loads and in Take and Hold this would be undesirable behaviour.

**Comment by pvtpaula** [comment]
Thank you for the suggestion. I searched the level for anything misplaced. The only spawnpoints i've set, where those within the supplypoints. Out of the "any" Prefabs i only used the [LEVEL] and a few ladders (already tried removing those). For the sandbox test i build it like a sandbox level. I didn't put both down.

I could try uploading the level or something or taking srceenshots. But i think i gotta start anew and do more tests along the way. To, mabe find what i did wrong. 
It Totally puzzles me, the Sosigs get spawned and all. I can even see the table i'm supposed to be. But im Stuck at the scoreboard, literally. Can't TP away or move, only my 6D movement comes through.

I only used bougth assets, mabe some where bad? I have too little experience to say.

**Comment by nrgill28** [comment]
Unfortunately if what I described above isn't the case then I have no idea. The only way I'd be able to help is if I had the scene to poke around in and if you're using paid assets then you can't send me your project (Since you're probably missing the rights to redistribute the paid assets).

I would recommend opening the unmodified Take and Hold debug scene and exporting that to verify it does completely work first, then going ahead and building off that to remake your scene. If the unmodified debug scene does not work, or you are able to recreate the issue in the scene without using paid assets then please open a new issue with more details and we can continue from there.
