### ISSUE TITLE
Hello guys, i have a problem with updating my unity project.

### ISSUE THREAD

**Issue by pvtpaula** [Nolenz/WurstMod#30]
Hello, after the holidays i got back into making my map. And i found the problem with my first mapping attempt, you can not put the map below 0 otherwise you will not be able to move.

Now to my problem, the map is up and running and you can download it. But it is in 2.0.0.0. an now i wanted to update it. but when i put the .deli into the plugin folder and remove .dll unity will not recognise it and i can not export the files.

I get that error message.

Assets/Scripts/EnumPicker.cs(134,30): error CS0246: The type or namespace name `WurstMod' could not be found. Are you missing an assembly reference?

I really liked to have it in 2.0.2.0 so it is easier for everyone.
is there something i did wrong, or did i use the wrong file?

Edit:
Today I tried updating the .dll file with the 2.0.1.0 realease, that seemed to work but then if i tried to place Holds or Spawns or anything they just get put down as a named Empty, so there is nothing left, then if i reimport the workbench it works but the .dll file gets replaced as well.

**Comment by nrgill28** [comment]
Please make sure to read the release notes entirely. From the [v2.0.2 release notes](https://github.com/Nolenz/WurstMod/releases/tag/v2.0.2.0):
> To upgrade a Unity project to v2.0.2.0 replace the old WurstMod.dll in your plugins folder with the new version, found below.  

So the fix here is instead of downloading the `.deli` file, download the `.dll`. If you want to get a clean slate, you can remove all of the files imported from the workbench file, re-import it and then replace the `WurstMod.dll` in the plugins folder with the most recent one. 

In future releases I will make the process of updating a Unity project more clear with better formatting.
