### ISSUE TITLE
Issues with Terrain

### ISSUE THREAD

**Issue by nrgill28** [Nolenz/WurstMod#9]
I have noticed a few issues with using Terrain in an exported map;

- Terrain Layer textures and shadows are reduced to extremely low resolutions in-game. Not sure what causes this.
- Bullet physics are *really* slow in some situations when colliding with terrain. I investigated this a bit and it gets really bad when firing at parts of terrain where the bullet can potentially pass through it's surface multiple times. I noticed in the PMat script there was an 'Impenetrable' option, though it doesn't seem to do anything here.

**Comment by Nolenz** [comment]
I don't recommend using Unity Terrain. I included enough handling to make it not explode immediately because someone asked me to, but I don't think it will ever work due to shader shenanigans (cannot successfully import new shaders for unknown reasons, and the proper Unity Terrain shaders were not included in the build of H3VR so we're kinda out of luck.)

**Comment by Frityet** [comment]
I would recommend using Alloy on the unity asset store for shaders, it was
developed for H3

**Comment by NikoWZRD** [comment]
Is this what's causing *extremely* awful dropped frames when you fire into angled Terrain?  I've noticed it when I have terrain as a backdrop and a few stray rounds hit it. That's a shame, I wonder how Anton does it.

**Comment by nrgill28** [comment]
There's enough issues with unity terrain that I think it's safe to say even if there is a fix, it's not worth the effort.
